BUNDLE_NAME = K3AAutoBrightness
K3AAutoBrightness_FILES = Switch.x
K3AAutoBrightness_FRAMEWORKS = UIKit
K3AAutoBrightness_PRIVATE_FRAMEWORKS = GraphicsServices
K3AAutoBrightness_LIBRARIES = flipswitch
K3AAutoBrightness_INSTALL_PATH = /Library/Switches

#ADDITIONAL_CFLAGS = 
#ADDITIONAL_LDFLAGS = 

include ../theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/library.mk
include $(THEOS_MAKE_PATH)/bundle.mk
